app = "acca0c6c-web"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile.web.ui.hstai"

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  IdentitySettings__Authority = "https://acca0c6c-ids.fly.dev/"
  IdentitySettings__TokenEndpoint = "https://acca0c6c-ids.fly.dev/connect/token"
  IdentitySettings__UserInformationEndpoint = "https://acca0c6c-ids.fly.dev/connect/userinfo"
  IdentitySettings__AuthorizationEndpoint = "https://acca0c6c-ids.fly.dev/connect/authorize"
  IdentitySettings__SelfUrl = "https://acca0c6c-web.fly.dev/"
  IdentitySettings__MetadataAddress = "https://acca0c6c-ids.fly.dev/.well-known/openid-configuration"
  IdentitySettings__ApiUrl = "https://acca0c6c-host.fly.dev/"
  ApiSettings__BaseUrl = "https://acca0c6c-host.fly.dev/"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm.cpu_kind]]
  count = 1
  kind = "shared"

[[vm.memory]]
  size_mb = 1024